name: multiple_countdown_timer
description: App para gestionar multiples countdown timers

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.6.5
  clean_core: ^1.3.4-SNAPSHOT.20221002

  #Time

  #Notifications & Dialogs
  awesome_dialog: ^3.0.1

  #Splash, intro, tutorials
  introduction_screen: ^3.0.1
  flutter_native_splash: ^2.2.9
  animated_theme_switcher: ^2.0.5

  #DB
  objectbox: ^1.6.0
  objectbox_flutter_libs: ^1.6.0
  path_provider: ^2.0.11
  flat_buffers: ^2.0.5
  clean_repo_objectbox: ^1.1.0-RELEASE.20221002

  cupertino_icons: ^1.0.2

  circular_countdown_timer:
    path: ../../Forks/circular_countdown_timer

dev_dependencies:
  flutter_test:
    sdk: flutter

  #DB code generation
  build_runner: ^2.2.0
  objectbox_generator: ^1.6.0

  flutter_native_splash: ^2.2.9
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
